version: development
# auth.enabled & auth.appToken are set by `deno task seed`
s3:
  enabled: true
  endpoint: localhost
  port: 9000
  useSSL: false
  accessKey: openhotel
  secretKey: openhotel
  region: us-east-1
  bucket: static
